FROM node

ENV RESIN_TOKEN_KEY youcandefineyourown
EXPOSE 3010

RUN git clone https://github.com/rizkisunaryo/resin-ws-drone.git
WORKDIR /resin-ws-drone

RUN npm install
CMD ["node", "executables/ws.js"]
